version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: mobility
    versions:
    - 1.0.3
    - 1.0.5
    - 1.0.6
    - 1.0.7
    - 1.1.0
    - 1.1.1
  - dependency-name: railties
    versions:
    - 6.1.1
    - 6.1.2.1
    - 6.1.3
  - dependency-name: activerecord
    versions:
    - 6.1.1
    - 6.1.2.1
    - 6.1.3
